const types = {
    FETCH_DATA_REQUEST: "FETCH_DATA_REQUEST",
    FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
    FETCH_DATA_CLEAR: "FETCH_DATA_CLEAR",
    FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",

    FETCH_DATA_SEARCH_REQUEST: "FETCH_DATA_SEARCH_REQUEST",
    FETCH_DATA_SEARCH_SUCCESS: "FETCH_DATA_SEARCH_SUCCESS",
    FETCH_DATA_SEARCH_CLEAR: "FETCH_DATA_SEARCH_CLEAR",
    FETCH_DATA_SEARCH_FAILURE: "FETCH_DATA_SEARCH_FAILURE",

    SAVE_FILTER_ITEM: "SAVE_FILTER_ITEM",
    CLEAR_FILTER_ITEM: "CLEAR_FILTER_ITEM",
}

export default types;